### ISSUE TITLE
`capture_default_str` on an `std::array`

### ISSUE THREAD

**Issue by gouarin** [henryiii/CLI11#1135]
Since the new release of CLI11 (2.5), this short example doesn't compile with clang 17.0.6. I haven't tested it with other compilers.

```cpp
#include <array>

#include <CLI/CLI.hpp>

int main(int argc, char** argv)
{
    std::array<int, 2> a{0, 1};
    CLI::App app{"My app"};
    app.add_option("--a", a, "an array")->capture_default_str();
    app.parse(argc, argv);

    return 0;
}
```

with the following error

```
In file included from cli11_test.cpp:3:
In file included from /Users/loic/mambaforge/envs/samurai-test/include/CLI/CLI.hpp:38:
/Users/loic/mambaforge/envs/samurai-test/include/CLI/App.hpp:551:20: error: no matching function for call to 'checked_to_string'
  551 |             return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loic/mambaforge/envs/samurai-test/include/CLI/App.hpp:550:79: note: while substituting into a lambda expression here
  550 |         Option *opt = add_option(option_name, fun, option_description, false, [&variable]() {
      |                                                                               ^
cli11_test.cpp:12:9: note: in instantiation of function template specialization 'CLI::App::add_option<std::array<int, 2>, std::array<int, 2>, (CLI::detail::enabler)0>' requested here
   12 |     app.add_option("--a", a, "an array")->capture_default_str();
      |         ^
/Users/loic/mambaforge/envs/samurai-test/include/CLI/TypeTools.hpp:456:6: note: candidate template ignored: substitution failure [with T1 = std::array<int, 2>, T2 = std::array<int, 2>, T = std::array<int, 2> &, $3 = 0]: call to 'to_string' is ambiguous
  456 | auto checked_to_string(T &&value) -> decltype(to_string(std::forward<T>(value))) {
      |      ^                                        ~~~~~~~~~
/Users/loic/mambaforge/envs/samurai-test/include/CLI/TypeTools.hpp:465:13: note: candidate template ignored: requirement '!std::is_same<std::array<int, 2>, std::array<int, 2>>::value' was not satisfied [with T1 = std::array<int, 2>, T2 = std::array<int, 2>, T = std::array<int, 2> &]
  465 | std::string checked_to_string(T &&) {
      |             ^
1 error generated.
```

I think it's a bug. Could you confirm this or tell me what has changed since version 2.4 ?

**Comment by phlptp** [comment]
I did verify this is present on other compilers, and that the code compiles on 2.4.2.   Still investigating the why question yet.   Not entirely convinced it was doing the right thing before, but likely has something to do with fixing the string output for tuples which was a bug that got fixed in 2.5.     I don't have time right now to debug further, but I am adding your example as one of the tests so should get it resolved soon.
