### ISSUE TITLE
Build failure with catch 3.10.0

### ISSUE THREAD

**Issue by jamesjer** [henryiii/CLI11#1236]
With catch 3.10.0 and cli11 2.6.0, compilation of a test fails:
```
In file included from /usr/include/catch2/catch_test_macros.hpp:11,
                 from /usr/include/catch2/catch_template_test_macros.hpp:20,
                 from /builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/catch.hpp:14,
                 from /builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/app_helper.hpp:15,
                 from /builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:8:
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp: In function ‘void CATCH2_INTERNAL_TEST_9()’
:
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:153:5: error: expected ‘,’ or ‘;’ before ‘do
’
  153 |     CHECK(result);
      |     ^~~~~
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp: In function ‘void CATCH2_INTERNAL_TEST_26()
’:
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:356:5: error: expected ‘,’ or ‘;’ before ‘if
’
  356 |     if(pstring_start > 0) {
      |     ^~
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:359:7: error: ‘else’ without a previous ‘if’
  359 |     } else {
      |       ^~~~
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp: In function ‘void CATCH2_INTERNAL_TEST_30()
’:
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:396:5: error: expected ‘,’ or ‘;’ before ‘tr
y’
  396 |     try {
      |     ^~~
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:402:7: error: expected primary-expression be
fore ‘catch’
  402 |     } catch(const CLI::HorribleError & /*he*/) {
      |       ^~~~~
/builddir/build/BUILD/cli11-2.6.0-build/CLI11-2.6.0/tests/FuzzFailTest.cpp:405:7: error: expected primary-expression be
fore ‘catch’
  405 |     } catch(const CLI::ParseError & /*e*/) {
      |       ^~~~~
```

Adding a semicolon to the end of each `INFO` invocation in the file (lines 152, 354, and 395) leads to a good build.

**Comment by phlptp** [comment]
curious, wonder why that works with 3.11 and some other versions, but not 3.10

**Comment by jamesjer** [comment]
So it does work with 3.11?  If 3.10 is the odd one out, then maybe you shouldn't worry about it.  I see from the changelogs that catch upstream messed with the INFO, etc. macros in both 3.10 and 3.11.

**Comment by phlptp** [comment]
One of our CI jobs runs it with Catch 3.11  (latest on home brew on a mac build).  [CI Job](https://github.com/CLIUtils/CLI11/actions/runs/18653005182/job/53175195142)   The auto download looks like 2.13 right now.  On those when I expand them it shows a double `;` if  I add the semicolon.  Though I admit in the code looks a bit odd to leave it off.
