### ISSUE TITLE
std::array option does not compile since CLI11 2.5.0

### ISSUE THREAD

**Issue by na-trium-144** [henryiii/CLI11#1222]
This code was working with CLI11 2.4.1 (and 2.4.2), but does not compile with 2.5.0. Is this a bug or a design change?
```cpp
#include <CLI/CLI.hpp>
#include <iostream>

int main(int argc, char **argv) {
    CLI::App app;
    std::array<int, 2> size = {30, 10};
    app.add_option("-s,--size", size, "Width and height");
    CLI11_PARSE(app, argc, argv);
    std::cout << "width=" << size[0] << ", height=" << size[1] << std::endl;
}
```

Compiler output (g++-11)
```
In file included from ../subprojects/CLI11-2.5.0/include/CLI/CLI.hpp:38,
                 from ../clitest.cpp:1:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp: In instantiation of ‘CLI::Option* CLI::App::add_option(std::string, AssignTo&, std::string) [with AssignTo = std::array<int, 2>; ConvertTo = std::array<int, 2>; typename std::enable_if<(! std::is_const<ConvertTo>::value), CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0; std::string = std::__cxx11::basic_string<char>]’:
../clitest.cpp:7:19:   required from here
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:551:71: error: no matching function for call to ‘checked_to_string<std::array<int, 2>, std::array<int, 2> >(std::array<int, 2>&)’
  551 |             return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from ../subprojects/CLI11-2.5.0/include/CLI/CLI.hpp:26,
                 from ../clitest.cpp:1:
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:456:6: note: candidate: ‘template<class T1, class T2, class T, typename std::enable_if<std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value, CLI::detail::enabler>::type <anonymous> > decltype (CLI::detail::to_string(forward<T>(value))) CLI::detail::checked_to_string(T&&)’
  456 | auto checked_to_string(T &&value) -> decltype(to_string(std::forward<T>(value))) {
      |      ^~~~~~~~~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:456:6: note:   template argument deduction/substitution failed:
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp: In substitution of ‘template<class T1, class T2, class T, typename std::enable_if<std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value, CLI::detail::enabler>::type <anonymous> > decltype (CLI::detail::to_string(forward<T>(value))) CLI::detail::checked_to_string(T&&) [with T1 = std::array<int, 2>; T2 = std::array<int, 2>; T = std::array<int, 2>&; typename std::enable_if<std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value, CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0]’:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:551:71:   required from ‘CLI::Option* CLI::App::add_option(std::string, AssignTo&, std::string) [with AssignTo = std::array<int, 2>; ConvertTo = std::array<int, 2>; typename std::enable_if<(! std::is_const<ConvertTo>::value), CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0; std::string = std::__cxx11::basic_string<char>]’
../clitest.cpp:7:19:   required from here
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:456:56: error: call of overloaded ‘to_string(std::array<int, 2>&)’ is ambiguous
  456 | auto checked_to_string(T &&value) -> decltype(to_string(std::forward<T>(value))) {
      |                                               ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:430:20: note: candidate: ‘std::string CLI::detail::to_string(T&&) [with T = std::array<int, 2>&; typename std::enable_if<(((((! std::is_convertible<T, std::__cxx11::basic_string<char> >::value) && (! std::is_constructible<std::__cxx11::basic_string<char>, T>::value)) && (! CLI::detail::is_ostreamable<T>::value)) && CLI::detail::is_tuple_like<S>::value) && (CLI::detail::type_count_base<T>::value >= 2)), CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0; std::string = std::__cxx11::basic_string<char>]’
  430 | inline std::string to_string(T &&value) {
      |                    ^~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:392:20: note: candidate: ‘std::string CLI::detail::to_string(T&&) [with T = std::array<int, 2>&; typename std::enable_if<((((! std::is_convertible<T, std::__cxx11::basic_string<char> >::value) && (! std::is_constructible<std::__cxx11::basic_string<char>, T>::value)) && (! CLI::detail::is_ostreamable<T>::value)) && CLI::detail::is_readable_container<T>::value), CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0; std::string = std::__cxx11::basic_string<char>]’
  392 | inline std::string to_string(T &&variable) {
      |                    ^~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp: In instantiation of ‘CLI::Option* CLI::App::add_option(std::string, AssignTo&, std::string) [with AssignTo = std::array<int, 2>; ConvertTo = std::array<int, 2>; typename std::enable_if<(! std::is_const<ConvertTo>::value), CLI::detail::enabler>::type <anonymous> = (CLI::detail::enabler)0; std::string = std::__cxx11::basic_string<char>]’:
../clitest.cpp:7:19:   required from here
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:465:13: note: candidate: ‘template<class T1, class T2, class T, typename std::enable_if<(! std::is_same< <template-parameter-1-1>, <template-parameter-1-2> >::value), CLI::detail::enabler>::type <anonymous> > std::string CLI::detail::checked_to_string(T&&)’
  465 | std::string checked_to_string(T &&) {
      |             ^~~~~~~~~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:465:13: note:   template argument deduction/substitution failed:
../subprojects/CLI11-2.5.0/include/CLI/TypeTools.hpp:464:80: error: no type named ‘type’ in ‘struct std::enable_if<false, CLI::detail::enabler>’
  464 |           enable_if_t<!std::is_same<T1, T2>::value, detail::enabler> = detail::dummy>
      |                                                                                ^~~~~
In file included from ../subprojects/CLI11-2.5.0/include/CLI/CLI.hpp:38,
                 from ../clitest.cpp:1:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:550:33: error: no matching function for call to ‘CLI::App::add_option(std::string&, CLI::App::add_option<std::array<int, 2> >(std::string, std::array<int, 2>&, std::string)::<lambda(const results_t&)>&, std::string&, bool, CLI::App::add_option<std::array<int, 2> >(std::string, std::array<int, 2>&, std::string)::<lambda()>)’
  550 |         Option *opt = add_option(option_name, fun, option_description, false, [&variable]() {
      |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  551 |             return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  552 |         });
      |         ~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:542:13: note: candidate: ‘template<class AssignTo, class ConvertTo, typename std::enable_if<(! std::is_const<ConvertTo>::value), CLI::detail::enabler>::type <anonymous> > CLI::Option* CLI::App::add_option(std::string, AssignTo&, std::string)’
  542 |     Option *add_option(std::string option_name,
      |             ^~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:542:13: note:   template argument deduction/substitution failed:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:550:33: note:   candidate expects 3 arguments, 5 provided
  550 |         Option *opt = add_option(option_name, fun, option_description, false, [&variable]() {
      |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  551 |             return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  552 |         });
      |         ~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:613:13: note: candidate: ‘template<class T, typename std::enable_if<(std::is_const< <template-parameter-1-1> >::value && std::is_constructible<std::__cxx11::basic_string<char>, T>::value), CLI::detail::enabler>::type <anonymous> > CLI::Option* CLI::App::add_option(std::string, T&)’
  613 |     Option *add_option(std::string option_name, T &option_description) {
      |             ^~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:613:13: note:   template argument deduction/substitution failed:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:550:33: note:   candidate expects 2 arguments, 5 provided
  550 |         Option *opt = add_option(option_name, fun, option_description, false, [&variable]() {
      |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  551 |             return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  552 |         });
      |         ~~
In file included from ../subprojects/CLI11-2.5.0/include/CLI/App.hpp:1478,
                 from ../subprojects/CLI11-2.5.0/include/CLI/CLI.hpp:38,
                 from ../clitest.cpp:1:
../subprojects/CLI11-2.5.0/include/CLI/impl/App_inl.hpp:160:22: note: candidate: ‘CLI::Option* CLI::App::add_option(std::string, CLI::callback_t, std::string, bool, std::function<std::__cxx11::basic_string<char>()>)’
  160 | CLI11_INLINE Option *App::add_option(std::string option_name,
      |                      ^~~
../subprojects/CLI11-2.5.0/include/CLI/impl/App_inl.hpp:164:67: note:   no known conversion for argument 5 from ‘CLI::App::add_option<std::array<int, 2> >(std::string, std::array<int, 2>&, std::string)::<lambda()>’ to ‘std::function<std::__cxx11::basic_string<char>()>’
  164 |                                      std::function<std::string()> func) {
      |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
In file included from ../subprojects/CLI11-2.5.0/include/CLI/CLI.hpp:38,
                 from ../clitest.cpp:1:
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:605:13: note: candidate: ‘CLI::Option* CLI::App::add_option(std::string)’
  605 |     Option *add_option(std::string option_name) {
      |             ^~~~~~~~~~
../subprojects/CLI11-2.5.0/include/CLI/App.hpp:605:13: note:   candidate expects 1 argument, 5 provided
ninja: build stopped: subcommand failed.
```

**Comment by phlptp** [comment]
can you try in main, I think this issue was resolved, and would be fixed in the next release.

**Comment by phlptp** [comment]
Will close this when we get the 2.6 release out
